/*
This file was generated by GitHub Copilot based on the contents of customers.js and db.js. 
*/
const express = require('express');
const router = express.Router();
const db = require('../db');

router.get('/', (req, res) => {
  db.query('SELECT * FROM Locations', (err, results) => {
    if (err) throw err;
    res.render('locations/index', { locations: results });
  });
});

router.post('/', (req, res) => {
  const { locationName } = req.body;
  db.query('INSERT INTO Locations (locationName) VALUES (?)', [locationName], (err) => {
    if (err) throw err;
    res.redirect('/locations');
  });
});

router.get('/delete/:id', (req, res) => {
  const { id } = req.params;
  db.query('DELETE FROM Locations WHERE locationID = ?', [id], (err) => {
    if (err) throw err;
    res.redirect('/locations');
  });
});

module.exports = router;